-- Create study_group_members table
CREATE TABLE IF NOT EXISTS public.study_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES public.study_groups(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    role TEXT DEFAULT 'member', -- 'admin', 'member'
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(group_id, user_email)
);

-- Enable RLS
ALTER TABLE public.study_group_members ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view members of groups" ON public.study_group_members
    FOR SELECT USING (true);

CREATE POLICY "Users can join groups" ON public.study_group_members
    FOR INSERT WITH CHECK (true); -- ideally check auth.uid() or email match

CREATE POLICY "Users can leave groups" ON public.study_group_members
    FOR DELETE USING (true); -- ideally check email match

-- Update study_groups member count function (optional but good for performance)
CREATE OR REPLACE FUNCTION update_member_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.study_groups
        SET members = members + 1
        WHERE id = NEW.group_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.study_groups
        SET members = members - 1
        WHERE id = OLD.group_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_group_member_count ON public.study_group_members;
CREATE TRIGGER update_group_member_count
AFTER INSERT OR DELETE ON public.study_group_members
FOR EACH ROW EXECUTE FUNCTION update_member_count();
